server:
  servlet:
    context-path: /haolifa

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.deepsoft.haolifa.model.domain.*


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:logback-spring.xml
