server:
  servlet:
    context-path: /haolifa
    session:
      timeout: 1h
      cookie:
        http-only: true
        max-age: 1h

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.deepsoft.haolifa.model.domain.*


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置日志存储路径
log:
  path: /data/log/haolifa

project:
   url: http://47.105.36.56

my:
  security:
    image:
      width: 60
      height: 40
      expire-sec: 60
      length: 4