server:
  port: 8081
  servlet:
    context-path: /haolifa

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.deepsoft.haolifa.model.domain.*

