server:
  port: 8081
  servlet:
    context-path: /haolifa

spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haolifa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 15
      idle-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 10000ms



mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.deepsoft.haolifa.model.domain.*

