CREATE TABLE `order_product`
(
    `id`                         int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `create_time`                timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`                timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user`                int(11) NOT NULL COMMENT '创建用户',
    `update_user`                int(11) NOT NULL DEFAULT '0' COMMENT '更新用户',
    `order_no`                   varchar(64)    NOT NULL COMMENT '订单编号（目前暂时和合同编号一致）',
    `order_contract_no`          varchar(128)   NOT NULL DEFAULT '' COMMENT '合同编号',
    `order_status`               tinyint(4) NOT NULL DEFAULT '0' COMMENT '订单状态',
    `order_contract_url`         varchar(128)   NOT NULL DEFAULT '' COMMENT '订单合同url',
    `order_contract_extend_url`  varchar(128)   NOT NULL DEFAULT '' COMMENT '订单合同url（价格隐藏）',
    `technical_require`          varchar(1024)  NOT NULL DEFAULT '[{"name":"","xinhao":"","guige":"","num":"","biaozhun":"","lianjiek":"","jiaodu":"","zhongxinju":"","xinshi":"","length":"","tuhao":"","jinniuju":"","jishuxinhao":"","guodupan":""}]' COMMENT '技术清单（技术员填写）',
    `finish_feedback_time`       varchar(32)    NOT NULL DEFAULT '' COMMENT '工厂反馈完成时间',
    `feedback_time_confirm_user` varchar(32)    NOT NULL DEFAULT '' COMMENT '反馈确认人',
    `purchase_feedback_time`     varchar(32)    NOT NULL DEFAULT '' COMMENT '采购反馈时间',
    `production_feedback_time`   varchar(32)    NOT NULL DEFAULT '' COMMENT '生产反馈时间',
    `assembly_shop`              varchar(32)    NOT NULL DEFAULT '' COMMENT '装配车间',
    `assembly_group`             varchar(32)    NOT NULL DEFAULT '' COMMENT '装配小组',
    `demand_name`                varchar(32)    NOT NULL DEFAULT '' COMMENT '需求方名称',
    `demand_agent_name`          varchar(32)    NOT NULL DEFAULT '' COMMENT '需求方代理人',
    `demand_phone`               varchar(32)    NOT NULL DEFAULT '' COMMENT '需求方电话',
    `demand_fax`                 varchar(32)    NOT NULL DEFAULT '' COMMENT '需求方传真',
    `demand_bank_name`           varchar(32)    NOT NULL DEFAULT '' COMMENT '需求开户银行',
    `demand_bank_card_no`        varchar(64)    NOT NULL DEFAULT '' COMMENT '需求开户银行账号',
    `supply_name`                varchar(32)    NOT NULL DEFAULT '' COMMENT '供应方',
    `supply_agent_name`          varchar(32)    NOT NULL DEFAULT '' COMMENT '供应方代理人',
    `supply_phone`               varchar(32)    NOT NULL DEFAULT '' COMMENT '供应方电话',
    `supply_fax`                 varchar(32)    NOT NULL DEFAULT '' COMMENT '供应方传真',
    `supply_bank_name`           varchar(32)    NOT NULL DEFAULT '' COMMENT '供应方开户银行',
    `contract_bank_card_no`      varchar(64)    NOT NULL DEFAULT '' COMMENT '供应方开户银行账号',
    `delivery_place`             varchar(64)    NOT NULL DEFAULT '' COMMENT '交货地点',
    `delivery_date`              varchar(64)    NOT NULL DEFAULT '' COMMENT '交货日期',
    `contract_sign_date`         varchar(32)    NOT NULL DEFAULT '' COMMENT '合同签订日期',
    `total_count`                int(11) NOT NULL DEFAULT '0' COMMENT '数量合计',
    `discount_total_price`       decimal(12, 4) NOT NULL DEFAULT '0.0000' COMMENT '优惠后总价',
    `total_price`                decimal(12, 4) NOT NULL DEFAULT '0.0000' COMMENT '总价',
    `special_require`            varchar(256)   NOT NULL DEFAULT '' COMMENT '特殊要求',
    `cargo_information`          varchar(256)   NOT NULL DEFAULT '' COMMENT '随货资料',
    `sign_board`                 varchar(256)   NOT NULL DEFAULT '' COMMENT '标牌',
    `acceptance_criteria`        varchar(256)   NOT NULL DEFAULT '' COMMENT '验收标准',
    `warranty_period`            varchar(256)   NOT NULL DEFAULT '' COMMENT '质保期限',
    `packaging_specification`    varchar(256)   NOT NULL DEFAULT '' COMMENT '包装规范',
    `remark`                     varchar(256)   NOT NULL DEFAULT '' COMMENT '备注',
    `deliver_status`             tinyint(4) NOT NULL DEFAULT '0' COMMENT '发货状态：0 待发货（默认） 1 部分发货 2 发货完成',
    `accessory`                  varchar(2048)  NOT NULL DEFAULT '' COMMENT '订单附件',
    `qualified_number`           int(11) NOT NULL DEFAULT '0' COMMENT '成品检验合格数量',
    `pressure_qualified_number`  int(11) NOT NULL DEFAULT '0' COMMENT '压力检测合格数量',
    `delivered_number`           int(11) NOT NULL DEFAULT '0' COMMENT '已发货数量',
    `received_account`           decimal(12, 2) NOT NULL DEFAULT '0.00' COMMENT '已收货款',
    `gen_picking_list`           tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否生成了领料单（0 否；1.是）',
    `is_check_material`          tinyint(4) NOT NULL DEFAULT '1' COMMENT '此订单是否需要核料（0 不需要；1 需要）',
    `task_status`                tinyint(4) NOT NULL DEFAULT '0' COMMENT '任务状态 0：未分配；1：已分配',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `uk_order_no` (`order_no`) USING BTREE,
    UNIQUE KEY `uk_order_contract_no` (`order_contract_no`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5138 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='成品订单表(商务销售发起订单流程的时候插入)';
