DROP TABLE IF EXISTS `iou`;
CREATE TABLE `order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` char(36) NOT NULL COMMENT '订单Id',
  `product_id` varchar(64) NOT NULL DEFAULT '' COMMENT '产品Id',
  `product_name` varchar(64) NOT NULL  DEFAULT '' COMMENT '产品名称',
  `product_model` varchar(64) NOT NULL DEFAULT '' COMMENT '产品型号',
  `lable` varchar(64) NOT NULL DEFAULT '' COMMENT '标签属性',
  `specifications` varchar(64) NOT NULL DEFAULT '' COMMENT '规格',
  `color` varchar(32) NOT NULL DEFAULT '' COMMENT '颜色',
  `number` varchar(32) NOT NULL DEFAULT '' COMMENT '数量',
  `material_description` varchar(1024) NOT NULL DEFAULT '' COMMENT '材质说明',
  `remark` varchar(1024) NOT NULL DEFAULT '' COMMENT '备注',
  `repayment_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '还款类型：1-到期一次性还本付息',
  `price` decimal(12,4) NOT NULL COMMENT '单价',
  `total_price` decimal(12,4) NOT NULL COMMENT '总价',
  `demand side` varchar(32) NOT NULL DEFAULT '' COMMENT '需求方',
  `supply side` varchar(32) NOT NULL DEFAULT '' COMMENT '供应方',
  `contract_number` varchar(32) NOT NULL DEFAULT '' COMMENT '合同编号',
  `contract_sign_date` varchar(32) NOT NULL DEFAULT '' COMMENT '合同签订日期',
--   `` tinyint(4) NOT NULL DEFAULT '0' COMMENT '出借人实际打款方式:0-还未打款 1-银行卡 2-微信 3-支付宝 4-其它；出借人确认放款时设置的实际打款方式。',
--   `actual_repayment_way` tinyint(4) NOT NULL DEFAULT '0' COMMENT '借款人实际还款方式:0-还未打款 1-银行卡 2-微信 3-支付宝 4-其它；借款人发布借条时设置的收款方式。',
--   `prefer_payment_way` tinyint(4) NOT NULL DEFAULT '0' COMMENT '借款人期望收款方式:0-未指定 1-银行卡 2-微信 3-支付宝 4-其它；借款人发布借条时设置的收款方式。',
--   `prefer_payment_account` varchar(128) NOT NULL DEFAULT '' COMMENT '借款人期望的收款账号',
--   `prefer_payment_remark` varchar(128) NOT NULL DEFAULT '' COMMENT '借款人选择其他的时候的补充说明',
--   `assign_user` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否指定出借人：0-未指定，1-指定',
--   `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '借条状态：0-已发布 1-已锁定待放款 2-已放款待确认 3-借款成功 4-已还款待确认 5-确认还款 6-取消借款 7-拒绝借款 8-已过募集期',
--   `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '借条类型：0-普通；1：推荐',
--   `overdue_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否逾期：0-未逾期 1-已逾期',
--   `appeal_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '申诉：0-未申诉 1-申诉中 2-申诉完成',
--   `pay_time` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '出借人放款时间（=上传放款凭证时间）',
--   `pay_confirm_time` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '借款人确认放款时间',
--   `repay_time` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '借款人还款时间（=上传还款凭证时间）',
--   `repay_confirm_time` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '出借人确认还款时间',
--   `payment_contract` varchar(128) NOT NULL DEFAULT '' COMMENT '借款合同pdf的路径，用于电子签章',
--   `repayment_receipt` varchar(128) NOT NULL DEFAULT '' COMMENT '还款凭证pdf的路径',
--   `tx_pay_hash` varchar(255) NOT NULL DEFAULT '' COMMENT '借条生效时，对应的区块链交易hash',
--   `tx_pay_block_num` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '借条生效时，对应的交易所在区块号',
--   `tx_repay_hash` varchar(255) NOT NULL DEFAULT '' COMMENT '借条还款时，对应的区块链交易hash',
--   `tx_repay_block_num` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '借条还款时，对应的交易所在区块号',
  `ctime` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '创建时间',
  `utime` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';
